[pt]
kind = "rt"
raygen = "pt_raygen"
closest = "ao_raychit"
miss = "ao_raymiss"

[deferred]
kind = "graphics"
vertex = "deferred_vert"
fragment = "deferred_frag"
use_depth = true

[light]
kind = "compute"
compute = "light_frag"

[tonemap]
kind = "graphics"
vertex = "light_vert"
fragment = "tonemap_frag"
use_depth = false

[taa]
kind = "compute"
compute = "taa_compute"

[atrous]
kind = "compute"
compute = "atrous"

[denoise_temporal]
kind = "compute"
compute = "denoise_temporal"

[sky]
kind = "compute"
compute = "sky"